[package]
name = "autoclap"
version = "0.2.10"
edition = "2021"
authors = ["Mihai Galos <mihaigalos@gmail.com>"]
description = "ğŸ‘ Auto-propagate Cargo.toml infos (name, version, author, repo) into app."
categories = ["command-line-utilities", "filesystem"]
keywords = ["disk", "disk-usage"]
repository = "https://github.com/mihaigalos/autoclap"
license = "MIT"

[dependencies]
clap = { version = "4.0.8", features = ["string"]}
